
lookup_index["WSJ_URL"] <- NA
lookup_index[match("CWCO", lookup_index$stock_sticker), "WSJ_URL"]<- "https://quotes.wsj.com/CWCO/financials"
lookup_index[match("SGRE.MC", lookup_index$stock_sticker), "WSJ_URL"]<- "https://quotes.wsj.com/ES/MABX/SGRE/financials"
lookup_index[match("ANA.MC", lookup_index$stock_sticker), "WSJ_URL"]<-"https://quotes.wsj.com/ES/MABX/ANA"
lookup_index[match("SCYR.MC", lookup_index$stock_sticker), "WSJ_URL"]<-"https://quotes.wsj.com/ES/MABX/SCYR/financials"
lookup_index[match("FCC.MC", lookup_index$stock_sticker), "WSJ_URL"]<-"https://quotes.wsj.com/ES/MABX/FCC/financials"
lookup_index[match("ABG.MC", lookup_index$stock_sticker), "WSJ_URL"]<-"https://quotes.wsj.com/ES/MABX/ABG/financials"
lookup_index[match("ITRI", lookup_index$stock_sticker), "WSJ_URL"]<-"https://quotes.wsj.com/ITRI/financials"
lookup_index[match("TTEK", lookup_index$stock_sticker), "WSJ_URL"]<-"https://quotes.wsj.com/TTEK/financials"
lookup_index[match("ARTNA", lookup_index$stock_sticker), "WSJ_URL"]<-"https://quotes.wsj.com/ARTNA/financials"
lookup_index[match("YORW", lookup_index$stock_sticker), "WSJ_URL"]<-"https://quotes.wsj.com/YORW/financials"
lookup_index[match("VIE.PA", lookup_index$stock_sticker), "WSJ_URL"]<-"https://quotes.wsj.com/FR/XPAR/VIE/financials"
lookup_index[match("GE", lookup_index$stock_sticker), "WSJ_URL"]<-"https://quotes.wsj.com/GE/financials"
lookup_index[match("XYL", lookup_index$stock_sticker), "WSJ_URL"]<-"https://quotes.wsj.com/XYL/financials"
lookup_index[match("WTS", lookup_index$stock_sticker), "WSJ_URL"]<-"https://quotes.wsj.com/WTS/financials"
lookup_index[match("ICL", lookup_index$stock_sticker), "WSJ_URL"]<-"https://quotes.wsj.com/ICL/financials"
lookup_index[match("AWK", lookup_index$stock_sticker), "WSJ_URL"]<-"https://quotes.wsj.com/AWK/financials"
lookup_index[match("3402.T", lookup_index$stock_sticker), "WSJ_URL"]<-"https://quotes.wsj.com/JP/XTKS/3402/financials"
lookup_index[match("6366.T", lookup_index$stock_sticker), "WSJ_URL"]<- "https://quotes.wsj.com/JP/XTKS/6366/financials"
lookup_index[match("7012.T", lookup_index$stock_sticker), "WSJ_URL"]<- "https://quotes.wsj.com/JP/XTKS/7012/financials"
lookup_index[match("6254.T", lookup_index$stock_sticker), "WSJ_URL"]<- "https://quotes.wsj.com/JP/XJAS/6254/financials"
lookup_index[match("7011.T", lookup_index$stock_sticker), "WSJ_URL"]<- "https://quotes.wsj.com/JP/XTKS/7011/financials"
lookup_index[match("6370.T", lookup_index$stock_sticker), "WSJ_URL"]<- "https://quotes.wsj.com/JP/XTKS/6370/financials"
lookup_index[match("FLC.AX", lookup_index$stock_sticker), "WSJ_URL"]<- "https://quotes.wsj.com/AU/XASX/FLC/financials"
lookup_index[match("SZ1.F", lookup_index$stock_sticker), "WSJ_URL"]<- "https://quotes.wsj.com/FR/XPAR/SEV/financials"
lookup_index[match("BFSA.DE", lookup_index$stock_sticker), "WSJ_URL"]<- "https://quotes.wsj.com/XE/XETR/BFSA/financials"
lookup_index[match("000157.KS", lookup_index$stock_sticker), "WSJ_URL"]<- "https://quotes.wsj.com/KR/XKRX/000157/financials"
lookup_index[match("SAL.MI", lookup_index$stock_sticker), "WSJ_URL"]<- "https://quotes.wsj.com/IT/XMIL/SAL/financials"
lookup_index[match("HYFXF", lookup_index$stock_sticker), "WSJ_URL"]<- "https://quotes.wsj.com/HYFXF/financials"
lookup_index[match("PTC", lookup_index$stock_sticker), "WSJ_URL"]<- "https://quotes.wsj.com/PTC/financials"
lookup_index[match("ANSS", lookup_index$stock_sticker), "WSJ_URL"]<- "https://quotes.wsj.com/ANSS/financials"
lookup_index[match("DSY.PA", lookup_index$stock_sticker), "WSJ_URL"]<- "https://quotes.wsj.com/FR/XPAR/DSY/financials"
